// Auto-generated by scripts/fetch-questions.ts
export const TOPICS: Record<string, string> = {
  "חוקי התנועה": "חוקי התנועה", // 501 questions
  "תמרורים": "תמרורים", // 361 questions
  "בטיחות": "בטיחות", // 305 questions
  "הכרת הרכב": "הכרת הרכב", // 106 questions
};
