import * as fs from "fs";
import * as path from "path";

const RESOURCE_ID = "bf7cb748-f220-474b-a4d5-2d59f93db28d";
const API_URL = `https://data.gov.il/api/3/action/datastore_search?resource_id=${RESOURCE_ID}&limit=2000`;

type Question = {
  id: string;
  topic: string;
  text: string;
  image?: string;
  answers: [string, string, string, string];
  correctIndex: 0 | 1 | 2 | 3;
};

function decodeEntities(str: string): string {
  return str
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}

function stripHtml(html: string): string {
  return decodeEntities(html.replace(/<[^>]*>/g, "")).trim();
}

function parseRecord(record: Record<string, string>): Question | null {
  try {
    const title2 = record.title2 ?? "";
    const description4 = record.description4 ?? "";
    const category = record.category ?? "";

    // Only ב questions — badge in the footer is «В» (Cyrillic В)
    if (!description4.includes("«В»")) return null;

    // "0641. Question text"
    const titleMatch = title2.match(/^(\d+)\.\s*([\s\S]+)$/);
    if (!titleMatch) return null;
    const id = titleMatch[1];
    const text = stripHtml(titleMatch[2].trim());

    // Extract individual <li>…</li> blocks
    const liMatches = [...description4.matchAll(/<li[^>]*>([\s\S]*?)<\/li>/gi)];
    // Take the first 4 answer <li> items
    const answerItems = liMatches.slice(0, 4);
    if (answerItems.length < 4) return null;

    const answers: string[] = [];
    let correctIndex = -1;

    for (let i = 0; i < 4; i++) {
      const liContent = answerItems[i][1];
      if (/id="correctAnswer\d+"/i.test(liContent)) {
        correctIndex = i;
      }
      answers.push(stripHtml(liContent));
    }

    if (correctIndex === -1) return null;

    // Optional image
    const imgMatch = description4.match(/<img[^>]+src="([^"]+)"/i);
    const image = imgMatch ? imgMatch[1] : undefined;

    const q: Question = {
      id,
      topic: category,
      text,
      answers: answers as [string, string, string, string],
      correctIndex: correctIndex as 0 | 1 | 2 | 3,
    };
    if (image) q.image = image;
    return q;
  } catch {
    return null;
  }
}

async function main() {
  console.log("Fetching from data.gov.il CKAN API…");
  const res = await fetch(API_URL);
  if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`);

  const data = (await res.json()) as { result?: { records?: Record<string, string>[] } };
  const records = data.result?.records ?? [];
  console.log(`Total records fetched: ${records.length}`);

  const questions: Question[] = [];
  let skipped = 0;

  for (const record of records) {
    const q = parseRecord(record);
    if (q) questions.push(q);
    else skipped++;
  }

  console.log(`ב questions parsed: ${questions.length} (skipped ${skipped})`);

  // Write questions.json
  const questionsOut = path.join(__dirname, "../lib/data/questions.json");
  fs.writeFileSync(questionsOut, JSON.stringify(questions, null, 2), "utf-8");
  console.log(`Written: ${questionsOut}`);

  // Derive unique topics and their question counts
  const topicMap: Record<string, number> = {};
  for (const q of questions) {
    topicMap[q.topic] = (topicMap[q.topic] ?? 0) + 1;
  }

  const topicEntries = Object.entries(topicMap).sort((a, b) => b[1] - a[1]);
  console.log("Topics:");
  for (const [t, n] of topicEntries) console.log(`  ${t}: ${n}`);

  // Write topics.ts — keys and Hebrew display labels are the same raw category string for now
  const lines = topicEntries.map(
    ([key, n]) => `  ${JSON.stringify(key)}: ${JSON.stringify(key)}, // ${n} questions`
  );
  const topicsTs = `// Auto-generated by scripts/fetch-questions.ts\nexport const TOPICS: Record<string, string> = {\n${lines.join("\n")}\n};\n`;
  const topicsOut = path.join(__dirname, "../lib/data/topics.ts");
  fs.writeFileSync(topicsOut, topicsTs, "utf-8");
  console.log(`Written: ${topicsOut}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
